### PR TITLE
Setup feed.xml

### PR DESCRIPTION
**Pull request by mktakuya**
Your Blog name is "Blog Name" ?????

### CODE REVIEW

**Comment by unasuke** [comment]
> Your Blog name is "Blog Name" ?????

No.

**Comment by unasuke** [comment]
Thank you for the pull request.

This repository is my private blog.
So, I have never decided lisence of the repository.
Could you waited until I determine the license?
And, could you accept the license(not decided yet)?

**Comment by unasuke** [comment]
I will apply the open-source-software license to this repository.
(e.g. MIT, BSD, GPL and so on)

**Comment by mktakuya** [comment]
> Could you waited until I determine the license?
> And, could you accept the license(not decided yet)?

OK :+1:
May the Force be with you.

**Comment by unasuke** [comment]
merge!!

**Comment by unasuke** [comment]
@mktakuya Thank you so much!

**Comment by mktakuya** [comment]
@unasuke :+1:

**Pull request merged**
